### ISSUE TITLE
Setup, provisioning, tearing down worker workflows

### ISSUE THREAD

**Issue by jozik** [emews/EQ-SQL#8]
Create and tear down backends from within ME code.
E.g., in R/Python:

- createSwiftBackend(specs)
- stopBackend()

The backend launching could utilize J/PSI (currently only Python implementation)

- Spec: https://exaworks.org/job-api-spec/specification.html 
- Python implementation: https://github.com/ExaWorks/psi-j-python

**Comment by jozik** [comment]
We'll create an initial use case, where the provisioning and teardown is sequential. 

Start Worker Pool 1 (wp1): handles tasks of type 1
Teardown wp1

Start Worker Pool 2 (wp2): handles tasks of type 2
Teardown wp2

wp1 has PPN1, wp2 has PPN2 (and potentially other differences, PROCS, walltime, etc.)

Initial implementation with bash, then try to extend to language specific capabilities (TBD).

**Comment by jozik** [comment]
I wonder if the new PSI/J SLURM executor (as of 9/7/21) could be used as what we could use in the follow up to the initial bash implementation.
PSI/J repo: https://github.com/ExaWorks/psi-j-python 
Mihael Hategan was also asking for SLURM executor testing.

**Comment by jozik** [comment]
From 9/24/21 discussion

For the worker pool we decided that we want the following semantics:

- Keep alive: exponential back off and ending at polling every second
- Kill: EQ_FINAL with specific data type

Also for the worker pools that are processing tasks but that are killed by walltime or other unexpected end before the tasks are completed, we’d want to be able to mark those tasks as **incomplete**, and differentiate them from the “in flight” tasks that are just being processed but which will finish. This way a worker pool can be restarted and continue processing tasks that are marked incomplete (due to worker pool failure).

**Comment by jozik** [comment]
From 3/2/22 discussion:

There are three types of worker pool setup and launch patterns:

1. Local set up (e.g., set up on HPC resource) + worker pool launch via local submit (w/ details about where to get tasks, i.e., where's the DB)
2. Local set up + remote worker pool launch (maybe this could be done relatively easily with funcX on the remote resource)
3. Remote set up (currently difficult to think about without some container approach) + remote worker pool launch

A new template for the builder that does worker pools is being created: https://github.com/emews/emews-project-creator/issues/6

**Comment by ncollier** [comment]
Implemented in worker_pool.py
