### ISSUE TITLE
fatal: role "EQ_SQL" does not exist

### ISSUE THREAD

**Issue by pedroliman** [emews/EQ-SQL#9]
It seems the sql() function within db-settings is confusing the database name with the database user name.

Maybe you have used the same database username and database name before, which is why it worked, but it didn't work here.

Suggested fix: in db-settings.sh, replace

psql --host=$DB_HOST --port=$DB_PORT $USER_ARG $DB_NAME $

with

psql --host=$DB_HOST --port=$DB_PORT --dbname=$DB_NAME --username=$DB_USER $

doing this here seems to have fixed my issues. In addition to that, you may want to remove the USER_ARG logic from the script.

**Comment by j-woz** [comment]
Thanks- I am trying to figure out what you are seeing.  Is it possible that a blank field is connecting two arguments?  If you turn on set -x you can see what is being done by the sql() function.

My intent is that DB_USER is normally empty and that no --username argument will be given.  I see that --user is wrong.  I am adding docs to see if we can converge on the intent here...

**Comment by j-woz** [comment]
Ok:   --user N      --username N      and    --username=N   all do the same thing.

**Comment by j-woz** [comment]
I see I used some ZSH syntax that breaks this in Bash - fixing now...
